### ISSUE TITLE
Button disabling 

### ISSUE THREAD

**Issue by ArtemSirobaba** [Rostyk27/nextjs-shop#3]
https://github.com/Rostyk27/nextjs-shop/blob/8146e365de82ea5dc98eb4e306c7e7c56bc3f952/components/product-parts/ProductButton.tsx#L42

 const [buttonText, setButtonText] = useState('Add to cart');
 
 
better to use something like
 const [isAdded, setIsAdded] = useState(false);
 
setIsAdded(true)

disabled={isAdded} 
 
 Why better?
 For example, use can use translation for text, (https://react.i18next.com/latest/usetranslation-hook)
 t`Add to cart`
with it, you can't use buttonText for disabling button usage.

**Comment by Rostyk27** [comment]
thanks for the great recommendation!
