### ISSUE TITLE
clsx function

### ISSUE THREAD

**Issue by ArtemSirobaba** [Rostyk27/nextjs-shop#4]
https://github.com/Rostyk27/nextjs-shop/blob/8146e365de82ea5dc98eb4e306c7e7c56bc3f952/components/product-parts/ProductImage.tsx#L23

improvement:
just check this package, really cool: arrays, string, objects can be converted to string style
https://www.npmjs.com/package/clsx

**Comment by Rostyk27** [comment]
thanks!
