### ISSUE TITLE
Props drilling

### ISSUE THREAD

**Issue by ArtemSirobaba** [Rostyk27/nextjs-shop#6]
https://github.com/Rostyk27/nextjs-shop/blob/8146e365de82ea5dc98eb4e306c7e7c56bc3f952/app/layout.tsx#L54

Can be a problem in the future, better to create context for it.
I count 3-4 prop for addToCart function. Not good for a big project (In the future)

**Comment by Rostyk27** [comment]
Yep, thanks for noticing. 

I used to have context for this project in pure React. 
https://github.com/Rostyk27/react-shop/blob/main/src/components/AddToCartContext.tsx

But in Next.js I was trying several scenarios of how to communicate between server and client components and ended up passing the server function via props😅  

Definitely will try to implement such a feature with context next time.
